name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - chore/build-fixes-build-compat

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          ADMIN_PAYMENT_TOKEN: ${{ secrets.ADMIN_PAYMENT_TOKEN }}
          ADMIN_INVOICE_TOKEN: ${{ secrets.ADMIN_INVOICE_TOKEN }}
        run: npm run build

      - name: Export public dir (optional if you have static assets)
        run: |
          mkdir -p public
          echo "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"></head><body><div id=\"app\"></div></body></html>" > public/index.html
          echo "<!doctype html><html><head><meta charset=\"utf-8\"></head><body>404</body></html>" > public/404.html

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: alloygator-nl


